### ISSUE TITLE
Pod install fails

### ISSUE THREAD

**Issue by UsmanINV8** [albert-zhang/AZWheelPickerView#2]
Installing AZWheelPickerView (0.1.1)

[!] Error installing AZWheelPickerView
[!] /usr/bin/git clone https://github.com/albert-zhang/AZWheelPickerView.git /var/folders/dg/ykbg2sgd0ybb6w0jgd7_yvqr0000gp/T/d20151022-3586-he3w6x --single-branch --depth 1 --branch 0.1.1

Cloning into '/var/folders/dg/ykbg2sgd0ybb6w0jgd7_yvqr0000gp/T/d20151022-3586-he3w6x'...
warning: Could not find remote branch 0.1.1 to clone.
fatal: Remote branch 0.1.1 not found in upstream origin

**Comment by albert-zhang** [comment]
Fixed the tags

**Comment by albert-zhang** [comment]
Fixed the tags
